CREATE TABLE IF NOT EXISTS JENRE
(
    ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORS
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL,
    SURNAME    VARCHAR(255) NOT NULL,
    PATRONYMIC VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS BOOKS
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE     VARCHAR(255) NOT NULL,
    ID_AUTHOR INT          NOT NULL,
    ID_JENRE  INT          NOT NULL,
    FOREIGN KEY (ID_AUTHOR) references AUTHORS (ID),
    FOREIGN KEY (ID_JENRE) references JENRE (ID)
);
