spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      port: 0
      database: library

server:
  port: 8080