spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000