version: '3.7'
services:

  application:
    build: .
    container_name: application
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
    container_name: mongo
    restart: always
    ports:
      - 27017:27017