spring:
  data:
    mongodb:
      port: 0
      database: library
    rest:
      base-path: /datarest

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true