spring:
  data:
    mongodb:
      port: 0
      database: library
    rest:
      base-path: /datarest

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, logfile

logging:
  file:
    name: spring-29/logs/logger.log
