spring:
  data:
    mongodb:
      port: 0
      database: library
    rest:
      base-path: /datarest

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
      enabled: true
    logfile:
      enabled: true

logging:
  level:
    root: INFO
  file:
    name: ./logs/logger.log
